name: End-to-end tests
on: [push] # Triggers the workflow every time you push code to GitHub

jobs:
  cypress-run:
    runs-on: ubuntu-latest # Runs on a virtual Linux machine
    steps:
      - name: Checkout # Step 1: Copy your code to the virtual server
        uses: actions/checkout@v4

      - name: Cypress run # Step 2: Install dependencies and run tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # Execute tests in Chrome browser